model:

  init_weights: null
  enc_filters: 1024
  labels: [ " ", "а", "б", "в", "г", "д", "е", "ж", "з", "и", "й", "к", "л", "м", "н", "о", "п", "р", "с", "т", "у", "ф", "х", "ц", "ч", "ш", "щ", "ъ", "ы", "ь", "э", "ю", "я" ]

  encoder:

    repeat: 5
    dropout: 0.0
    feat_in: 64

    blocks:
      - filters: 256
        repeat: 1
        kernel_size: 33
        stride: 4
        dilation: 1
        residual: false
        dropout: ${model.encoder.dropout}
        separable: true

      - filters: 256
        repeat: ${model.encoder.repeat}
        kernel_size: 33
        stride: 1
        dilation: 1
        residual: true
        dropout: ${model.encoder.dropout}
        separable: true

      - filters: 256
        repeat: ${model.encoder.repeat}
        kernel_size: 39
        stride: 1
        dilation: 1
        residual: true
        dropout: ${model.encoder.dropout}
        separable: true

      - filters: 512
        repeat: ${model.encoder.repeat}
        kernel_size: 51
        stride: 1
        dilation: 1
        residual: true
        dropout: ${model.encoder.dropout}
        separable: true

      - filters: 512
        repeat: ${model.encoder.repeat}
        kernel_size: 63
        stride: 1
        dilation: 1
        residual: true
        dropout: ${model.encoder.dropout}
        separable: true

      - filters: 512
        repeat: ${model.encoder.repeat}
        kernel_size: 75
        stride: 1
        dilation: 1
        residual: true
        dropout: ${model.encoder.dropout}
        separable: true

      - filters: 512
        repeat: 1
        kernel_size: 87
        stride: 1
        dilation: 2
        residual: false
        dropout: ${model.encoder.dropout}
        separable: true

      - filters: ${model.enc_filters}
        repeat: 1
        kernel_size: 1
        stride: 1
        dilation: 1
        residual: false
        dropout: ${model.encoder.dropout}
        separable: false

  decoder:
    feat_in: ${model.enc_filters}
    labels: ${model.labels}

optim:
  optimizer:
    name: 
      Adam
    params:
      lr: 1e-3
  scheduler:
    name:
      CosineAnnealing
    params:
      warmup_steps: 10
      max_steps: ${trainer.max_steps}


train_dataloader:
  num_workers: 2
  batch_size: 16
  prefetch_factor: 1
  dataset:
    manifest_name: train_opus/manifest.jsonl
    labels: ${model.labels}
    transforms:
      - name: mel_spectrogram
        params:
          sample_rate: 16000
          n_fft: 400
          win_length: 400
          hop_length: 160
          n_mels: ${model.encoder.feat_in}
      - name: log_scaler

val_dataloader:
  num_workers: ${train_dataloader.num_workers}
  batch_size: ${train_dataloader.batch_size}
  prefetch_factor: ${train_dataloader.prefetch_factor}
  dataset:
    manifest_name: test_opus/farfield/manifest.jsonl
    labels: ${model.labels}
    transforms:
      ${train_dataloader.dataset.transforms}

trainer:
  # resume_from_checkpoint: null
  val_check_interval: 1.0
  check_val_every_n_epoch: 2
  log_every_n_steps: 5
  precision: 32
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  accelerator: auto
  max_steps: 300
  devices: 1
