sample_rate: 16000

feature_extractor:
  _target_: torch.nn.Sequential
  _args_:
    - _target_: torchaudio.transforms.MelSpectrogram
      sample_rate: ${sample_rate}
      n_fft: 400
      win_length: 400
      hop_length: 160
      n_mels: 64
    - _target_: model.SpecScaler

model:
  _target_: model.load_model
  path: ./data/kws.onnx
  intra_threads: 1
  inter_threads: 4

inference:
  window_size_seconds: 1.0
  window_shift_seconds: 0.1
  avg_window_size: 3
  idx_to_keyword:
    - 'сбер'
    - 'джой'
    - 'афина'
    - 'салют'
    - ''
  threshold: 0.7
